version: '3.8'
services:
  project:
    build: ./01-starting-project 
    container_name: project
    ports:
    - "3000:3000"
    volumes:
    - ./01-starting-project:/app
    - /app/node_modules
    stdin_open: true
    tty: true
    
